### ISSUE TITLE
Merge 2.1.1 on to Master

### ISSUE THREAD

**Issue by gali8** [lkzhao/ElasticTransition#17] opened 2016-03-11 09:53 UTC
There are a couple of bugs in the version 2.0.1 (like viewControllerForKey(UITransitionContextFromViewControllerKey) exc_bad_instruction). They are fixed on 2.1.1.
Please merge on to master.

**Comment by gali8** [comment] 2016-03-13 17:00
Nope! There is a bug into the 2.1.1 version. 
I have a custom navigation controller that is the elastictransition delegate. Pushing a uitableviewcontroller, the scroll of the table view will be not recognized.
Anyway, my version of the 2.0.1 is ok (i just putted to optional a lot of variables).
Merge :)

**Comment by lkzhao** [comment] 2016-03-13 19:55
@gali8 
Thanks for you contribution. After looking at your PR, I dont think that `transitionContext` and `container` should be nilable. It increased code complexity and we have to do a lot of optional chaining.

The easy way to fix for these crashes that you are experiencing is just to check wether or not we are actually doing a transition before any callbacks that uses these variables. That is what I did for 2.1.1. The tableview bug is caused by another feature that I am adding. I want scrollview to trigger the elastic transition when the user scrolls to the top. I am fixing it right now and hopefully get the 2.1.1 branch merged today.

Again, thanks for the contribution! please let me know if you have any other concerns or experiencing any other bugs.

**Closed as completed** 2016-03-13 20:51 UTC
